# Generated by Django 3.2.21 on 2023-09-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('userpw', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('jdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
